version: "3"
services:
  app:
    image: dockerwithmetrics:latest
    ports:
      - "8080:8080"
    hostname: dockerwithmetrics

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    hostname: grafana