global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['dockerwithmetrics:8080'] #hostname:port